### PR TITLE
Unbalanced tree

### PR DESCRIPTION
**Pull request by taylo2allen**
Created the structure to run the WordCount args and implemented WordCount -b -frequency <file>.

### CODE REVIEW

**Comment by checkmate3001** [comment]
I think we are going about it wrong. I double checked the PDF and WordCount should only ever accept a single file.

There is a second program we have to write that will compare the results from two different files.

**Comment by taylo2allen** [comment]
I know wordCount is still only accepting one file but I was thinking ahead and thought we could use it with the document correlator when we make it

**Comment by checkmate3001** [comment]
Oh, okay. I see where you're heading with it.

**Comment by taylo2allen** [comment]
should we merge it or wait

**Comment by checkmate3001** [comment]
I think we can merge.

**Comment by taylo2allen** [comment]
just merged unbalanced_tree with master

**Pull request merged**
